# Generated by Django 3.0.9 on 2020-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=30)),
                ('contactEmail', models.CharField(max_length=200)),
                ('contactSubject', models.CharField(max_length=50)),
                ('contactMessage', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
